### ISSUE TITLE
Ingredient Custom Post Type

### ISSUE THREAD

**Issue by blupu** [simmerwp/simmer#74] opened 2015-07-28 16:32 UTC
Hi,

I think it would be nice to have a custom post type for ingredients. It would open a new and fascinating world where we can have image for ingredients, re-use them, maybe build shop list based on that... :-) (Or maybe have addon to import thematic ingredient list.)

*For the record, cooking vietnamese dishes, it has helped me to have images for some ingredients as I didn't know them before.*

**Comment by laralfield** [comment] 2015-07-30 12:05
Hi @blupu! Thank you so much for your feedback. This is a feature that we've had high on our list for a while now, and we are so looking forward to opening up the uses for ingredients and instructions data to include links, videos, and more rich media in the future. The shop feature you mention sounds especially fantastic for something like a small food business online, and many other types of startups, too. 

Do you have a location where you're currently food blogging? I'd love to follow along with any vietnamese dishes you've shared, and images in ingredients would be the perfect case for this as you mention.

I'm going to close this ticket because we use the Issues feature here to track bugs, vs. feature suggestions, but I'd love to continue the conversation here. So, please feel free to continue to comment even though you'll see the Issue is 'closed' and I will let you know as soon as these features are ready, here. 

Have a great day! ☀️

**Closed by laralfield** 2015-07-30 12:05 UTC

**Comment by blupu** [comment] 2015-08-01 09:34
Hi @laralfield, no problem about closing issues. I understand. I cook but I don't blog about cooking. For me it is a question of focus on my job - leading a digital department for a press group - but also on a side project who keeps me more and more busy: WP-AppKit. I mention it as it is why I've discovered Simmer. WP-AppKit is a plugin to build mobile apps and connect them to WordPress. Working on it, I am exploring fields where mobile apps are relevant: jobs, city guides, documentations, books... and of course cooking. Regarding vietnamese dishes, I have a really good book written by a French vietnamese with real recipes (as the taste is exactly what you experience in Vietnam). The author, probably knowing that non-vietnameses don't know so much about vietnamese ingredients, takes care to put photos everywhere in the book. I can assure you it's a really good idea as some of them were totaly unknown to me ;-) Thank you for your answers. I look forward to play with new features in Simmer.

**Comment by laralfield** [comment] 2015-08-04 20:22
@blupu This is a perfect example of the extendability into mobile apps. So awesome! Please feel free to continue to share your findings, and feel free to email me anytime lara@simmerwp.com. 

I am really excited for our "Rich Ingredients & Instructions" feature which will provide all of these features, in addition to the ability to link to a referral item from your ingredients list, include images, videos or GIFs in instructions, etc... Please feel free to email me anytime with suggestions or use cases.

**Comment by laralfield** [comment] 2016-08-09 02:38
Great ideas above! Adding the add-on label for future reference now.
